version: '7'

services:
  app:
    build: 
      context: .
      dockerfile: docker/app/Dockerfile
    command: flask run --host=0.0.0.0
    environment:
      - FLASK_ENV=development
      - DATABASE_URL=postgresql+psycopg2://postgres:postgres@db:5432/consignments
    ports:
      - 5001:5000
    volumes:
      - ./app:/app
    networks:
      - backend
    depends_on:
      - db
  
  web:
    build: ./docker/web
    command: npm start
    ports:
      - 3000:3000
    volumes:
      - ./assets:/assets
    depends_on:
      - app
  
  db:
    build: ./docker/db
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=consignments
      - POSTGRES_HOST_AUTH_METHOD=md5
    ports:
      - '5555:5432'
    networks:
      - backend
    volumes:
      - postgress_volume:/var/lib/postgresql/data

networks:
  backend:
    driver: bridge
    name: backend

volumes:
  postgress_volume: